<?php if ( $this->navigation->hasPages() ): ?>
  <?php $sublevel = ( isset($this->sublevel) ) ? $this->sublevel+1 : 0; ?>
  <?php if ($sublevel > 0): ?><li><?php endif; ?>
  <ul>
    <?php $cnt = 0; ?>
    <?php foreach ($this->navigation->getPages() as $page): ?>
      <li class="e<?php echo $sublevel; ?><?php echo ( $page->isActive() ) ? ' active' : ''; ?><?php echo ( $cnt==0 && $sublevel==0 ) ? ' first' : ''; ?>">
        <a href="<?php echo $page->getHref().'/'; ?>" title="<?php echo $page->getTitle(); ?>"><?php echo $page->getLabel(); ?></a>
      </li>
      <?php if ( $page->hasPages() ): ?>
          <?php echo $this->partial('_navigation.phtml', array('navigation' => $page, 'sublevel' => $sublevel)); ?>
      <?php endif; ?>
      <?php $cnt++; ?>
    <?php endforeach; ?>
  </ul>
  <?php if ($sublevel > 0): ?></li><?php endif; ?>
<?php endif; ?>
