<?xml version="1.0" encoding="UTF-8" ?>
<?php echo $this->doctype(); ?>

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
        echo $this->headTitle()."\n";
        echo $this->headScript()."\n";

        $this->loadSkin($this->skin);
        echo $this->headLink() . PHP_EOL;
    ?>
    <script type="text/javascript">
    /* <![CDATA[ */
        $(document).ready(function() {
            setExternalLinks();
        });
    /* ]]> */
    </script>
</head>

<body>
    <div id="pageWrapper">
        <div id="headerbox">
            <a href="/home/"><img src="/img/logo.png" id="logo" alt="" /></a>
            <div id="slogan">Ich leb in meiner eigenen Welt. Das ist ok, man kennt mich dort.</div>
        </div>
        <div id="statusbox">
            <?php echo $this->layout()->status; ?>
        </div>
        <div id="leftbox">
            <?php if (!$this->isSplash): ?>
                <div id="navigation">
                    <?php echo $this->partial('_navigation.phtml', array('navigation' => $this->navigation())); ?>
                </div>
            <?php endif; ?>
        </div>

        <?php echo $this->placeholder('rightbox'); ?>

        <div id="contentbox">
            <?php echo $this->layout()->content; ?>
        </div>
        <div id="footerbox">
            <div class="links">
                <a href='http://www.zcat.de/docs/hacker-emblem/'><img src='http://www.catb.org/hacker-emblem/glider.png' alt='hacker emblem' /></a>
            </div>
            <div class="rechts">
                <img class="microbanner" src="/img/microbanner/valid_xhtml.png" alt="Valid XHTML 1.0 Strict" /><br />
                <img class="microbanner" src="/img/microbanner/valid_css.png" alt="Valid CSS" /><br />
                <img class="microbanner" src="/img/microbanner/zend_framework.gif" alt="Zend Framework in action!" /><br />
                <img class="microbanner" src="/img/microbanner/jquery2.png" alt="jQuery in action!" /><br />
            </div>
            <div class="mitte">
                .:: <!--a href="/sitemap/"-->Sitemap<!--/a--> |
                <!--a href="/impressum/"-->Impressum<!--/a--> |
                <a href="mailto:foomy.code@arcor.de">Kontakt</a> |
                <!--a href="/faq/"-->FAQ<!--/a--> |
                <a href="http://www.spiegel.de/netzwelt/politik/0,1518,375970,00.html" rel="extern">Disclaimer</a>
                ::.<br />
                Designed &amp; programmed by Sascha Schneider<br />
                <p id="geekcode">
                    <a href="http://www.geekcode.com/" title="What is geek code?" rel="extern">GCS d-- s-:+ a C++$>(+++) UL P+ L+ E? W++ N+ o? K? w !O !M V? PS+ PE Y+ PGP+ t++>(+++) 5+ X+ R !tv b+ DI D G e-- h r- y?</a>
                </p>
            </div>
        </div>
    </div>
</body>
</html>
