<div class="head1">Logout erfolgreich...</div>
<div class="head2">...oder was du jetzt tun kannst!</div>

Du könntest zum Beispiel eines der folgenden Dinge tun:
<ul>
  <li>Einfach so weiter auf der Seite surfen.</li>
  <li>Oder du könntest ein gutes Buch lesen.</li>
  <li>Einen Film gucken.</li>
  <li>Oder vielleicht mal wieder deine Freundin schick ausführen.</li>
  <li>oder, oder, oder...</li>
</ul>
