<div id="bookmarks">
  <?php if (count($this->paginator) > 0): ?>
    <?php // echo $this->paginationControl($this->paginator, 'Sliding', 'bastel/_pagination_control.phtml'); ?>
    <div id="bookmarklist">
      <?php foreach ($this->paginator as $bookmark): ?>
        <div id="bm_<?php echo $bookmark->getId(); ?>" class="bookmark">
          <div class="thumbnail">
            <?php if ($bookmark->getPicture()!==null): ?>
              <img src="<?php echo $bookmark->getPicture(); ?>" alt="<?php echo $bookmark->getTitle(); ?>" />
            <?php endif; ?>
          </div>
          <div class="details">
            <div class="title">
              <a href="<?php echo $bookmark->getHref(); ?>"><?php echo $bookmark->getTitle(); ?></a>
            </div>
            <div class="comment"><?php echo $bookmark->getComment(); ?></div>
            <div class="tags fett">Testtag Tag2 Tag3und4</div>
            <div class="ctrl">
              <ul>
                <li><a href="/bookmarks/edit/bmid/<?php echo $bookmark->getId(); ?>">edit</a></li>
                <li id="delete_<?php echo $bookmark->getId(); ?>">delete</li>
              </ul>  
            </div>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
    <?php // echo $this->paginationControl($this->paginator, 'Sliding', 'bastel/_pagination_control.phtml'); ?>
  <?php endif; ?>
</div>
<script type="text/javascript">
/* <![CDATA[ */
    $(document).ready(function() {
        $('li').live('click', function() {
            var bookmarkId = $(this).attr('id').split('_').pop();

            $.post(
                'index/delete',
                { bookmarkId: bookmarkId },
                function(data) {
                    $('#bm_'+bookmarkId).remove();
                },
                'json'
            );
        });
    });
/* ]]> */
</script>
