<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="twoColRight">
	<article class="is_content">
		<div id="articletext">
			<h1>Bikinis strahlender Tag</h1>
			<p class="justify">
				Am 1. März 2004 ist der 50. Jahrestag der Detonation der US-Wasserstoffbombe "Bravo"
				auf dem Bikini-Atoll. Zwischen 1946 und 1958 testeten die USA auf dem Bikini- und dem
				benachbarten Eniwetok-Atoll annähernd 70 Atom- und Wasserstoffbomben. Der verheerendste
				Test fand am 1. März 1954 statt, bei dem durch die Detonation der Wasserstoffbombe mit
				dem Code-Namen "Bravo" hunderte Insulaner im Pazifik radioaktiv verseucht wurden.
			</p>
			<p>
				Am 01.03.1954 führten die USA im Rahmen der Operation CASTLE BRAVO
				ihren größten Atomtest auf dem Bikini Atoll der Marschall-Inseln durch.
				Eigentlich sollte die Testbombe BRAVO "nur" eine Sprengkraft von
				7 Megatonnen haben, tatsächlich war ihre Detonationsenergie genau
				doppelt so groß. Der radioaktive Fallout erstreckte sich über eine
				Fläche von 7.000 qkm. Die falschen Berechnungen der Bombenstärke führten
				dazu, daß das vorher abgesperrte Gefahrengebiet viel zu klein war,
				dadurch wurden 236 Insulaner und 28 US-Meteorologen verstrahlt. Durch den
				Feuerball völlig verwirrt, glaubten die 23 Matrosen an Bord des
				japanischen Fischkutters Fukuryu Maru (Glücklicher Drache) zunächst, die
				Sonne ginge in der falschen Richtung auf. Obwohl sie fast 200 km von
				"Ground Zero" entfernt waren, rieselte auch auf sie der Fallout nieder.
				Die Schiffsbesatzung wurde u.a. durch Einsteinium und Fermium verstrahlt,
				diese Isotope kannte man bis dahin nur aus der Physiktheorie. Fast alle
				Männer erkrankten an Leukämie, die bei mehreren zum Tod führte.
			</p>

			<h3>Ultrabomben für den Weltuntergang</h3>
			<p>
				Auf Grund der Verstrahlungsopfer beim BRAVO-Test sagte die US-Regierung
				den Test einer noch stärkeren Wasserstoffbombe ab. Die amerikanische
				"Super Giant" sollte eine Sprengenergie von 45 Megatonnen freisetzen.
				Hingegen zündete die sowjetische Regierung im Oktober 1961 auf der
				Nordmeer-Insel Nowaja Semlja eine Bombe mit einer Sprengkraft von
				55 bis 58 Megatonnen, die vom späteren Dissidenten Andrei Sacharow
				entwickelt worden war. Es handelte sich um den Prototyp der Bombe vom Typ
				"Iwan", die in geringer Stückzahl produziert worden ist. Eine solche Waffe
				hatte eine Sprengkraft von rund 100 Megatonnen, aber wegen
				Sicherheitsbedenken war die Sprengkraft für den Test reduziert worden.
				Die größten Wasserstoffbomben im US-Arsenal waren Bomben mit einer
				Sprengkraft von jeweils 24 Megatonnen, die nie in ihrer vollen Stärke
				getestet wurden. Die Mark-21 gehörte nur von 1955 bis 1957 zum Bestand; das
				Nachfolgemodell Mark-36 war von 1956 bis 1962 in Verwendung. Auf dem
				Reißbrett wurden noch stärkere Kaliber erdacht: So plante die US-Regierung
				zeitweilig die Entwicklung einer 200 Meg-atonnen-Bombe, die von einem
				fern-gesteuerten Bomber QB-52 Stratofortress abgeworfen werden sollte. Den
				Rekord hält der Ingenieur Bruno Augenstein von der amerikanischen RAND
				Corporation in Kalifornien. Er schlug den Bau einer Bombe mit einer
				Sprengkraft von 1 Gigatonne (= 1000 Megatonnen) vor. Auch spezielle
				Wasserstoffbomben mit einem Mantel aus Kobalt wurden vorgeschlagen.
				Kobalt-60 ist ein enorm starker Gammastrahler. Mit einer einzigen
				Kobaltbombe ließe sich die gesamte Erdatmosphäre über Jahre hinweg
				verstrahlen. Durch Zündung einer Wasserstoffbombe über der Arktis würde die
				polare Eiskappe schmelzen und eine riesige Welle freisetzen, die zahlreiche
				Länder überfluten würde. Auch ließe sich durch die Detonation mehrerer
				Wasserstoffbomben vor der kalifornischen Küste eine Tsunami-Welle auslösen,
				die den Westen der USA bis zu den Rocky Mountains überschwemmen würde.
			</p>
		</div>
	</article>
	<aside class="is_sidebar"></aside>
	<div class="clear"></div>
</div>
<?php include 'inc/html_foot.phtml'; ?>