<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="twoColRight">
	<article class="is_content"></article>
	<aside class="is_sidebar">
		<?php include 'inc/navigation.phtml'; ?>

		<!-- LATEST COMMENTS -->
		<div class="widget sidebar latestComments">
			<div class="head">Die neusten Kommentare</div>
			<div class="content">
				<div class="comment">
					<div><a href="javascript:;">War schon krass...</a></div>
					<span class="userinfo">Testuser; 15.02.2012 20.34 Uhr</span>
				</div>
				<div class="comment">
					<div><a href="javascript:;">Kuhler Artikel</a></div>
					<span class="userinfo">Testuser; 15.02.2012 16.24 Uhr</span>
				</div>
				<div class="comment">
					<div><a href="javascript:;">Auf was man da alles...</a></div>
					<span class="userinfo">Testuser; 14.02.2012 13.11 Uhr</span>
				</div>
				<div class="comment">
					<div><a href="javascript:;">Testkommentar</a></div>
					<span class="userinfo">Testuser; 12.02.2012 10.42 Uhr</span>
				</div>
				<div class="comment">
					<div><a href="javascript:;">Testkommentar</a></div>
					<span class="userinfo">Testuser; 11.11.2011 11.11 Uhr</span>
				</div>
			</div>
			<div class="foot"></div>
		</div>
	</aside>
	<div class="clear"></div>
</div>
<?php include 'inc/html_foot.phtml'; ?>