<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="oneColumn">
	<article class="is_content">
		<div id="gallery">
			<div class="mainview is_mainview">
				<img src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="">
			</div>
			<div class="thumbnails">
				<img class="thumbnail is_tNail is_tn1" data-id="1" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="">
				<span class="is_tnMeta1" data-imgsrc="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg"></span>
				<img class="thumbnail is_tNail is_tn2" data-id="2" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="">
				<span class="is_tnMeta2" data-imgsrc="/img/gallery/b808a9c0-pflanzen/klivie.jpg"></span>
				<img class="thumbnail is_tNail is_tn3" data-id="3" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="">
				<span class="is_tnMeta3" data-imgsrc="/img/gallery/b808a9c0-pflanzen/rose.jpg"></span>
				<img class="thumbnail is_tNail is_tn4" data-id="4" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="">
				<span class="is_tnMeta4" data-imgsrc="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg"></span>
				<img class="thumbnail is_tNail is_tn5" data-id="5" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="">
				<span class="is_tnMeta5" data-imgsrc="/img/gallery/b808a9c0-pflanzen/klivie.jpg"></span>
				<img class="thumbnail is_tNail is_tn6" data-id="6" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="">
				<span class="is_tnMeta6" data-imgsrc="/img/gallery/b808a9c0-pflanzen/rose.jpg"></span>
				<img class="thumbnail is_tNail is_tn7" data-id="7" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="">
				<span class="is_tnMeta7" data-imgsrc="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg"></span>
				<img class="thumbnail is_tNail is_tn8" data-id="8" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="">
				<span class="is_tnMeta8" data-imgsrc="/img/gallery/b808a9c0-pflanzen/klivie.jpg"></span>
				<img class="thumbnail is_tNail is_tn9" data-id="9" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="">
				<span class="is_tnMeta9" data-imgsrc="/img/gallery/b808a9c0-pflanzen/rose.jpg"></span>
			</div>
		</div>
	</article>
</div>
<?php include 'inc/html_foot.phtml'; ?>
