<?php include 'inc/html_head.phtml'; ?>
	<div id="content" class="twoColRight">
		<article class="is_content">
			<div id="galleries">
				<?php for ($i = 0; $i<5; $i++): ?>
				<div class="gallery is_gallery" data-galid="<?php echo $i; ?>">
					<div class="gallery-cover">
						<img class="cover-thumbnail rot-left is_rotLeft<?php echo $i; ?>" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="" style="z-index:5">
						<img class="cover-thumbnail rot-right is_rotRight<?php echo $i; ?>" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="" style="z-index:4">
						<img class="cover-thumbnail" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="" style="z-index:3">
					</div>
					<div class="gallery-title">
						Albumtitel
					</div>
				</div>
				<?php endfor; ?>
				<div class="clear"></div>
			</div>
		</article>
		<aside class="is_sidebar"></aside>
		<div class="clear"></div>
	</div>
<?php include 'inc/html_foot.phtml'; ?>