<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="oneColumn">
	<article id="impress" class="is_content">
		<section class="from">
			<h1>Diese Seiten wurden verbrochen von...</h1>
			<address class="real">
				Sascha Schneider<br>
				Merkurstraße 36<br>
				70565 Stuttgart-Rohr<br>
				<br>
				E-Mail: <span class="is_email">foomy.code@arcor.de</span>
			</address>
		</section>
		<section class="about">
			SirFoomy's Welt ist eine private Homepage und dient,
			keinerlei kommerziellem Zweck. Genau betrachtet dienen
			diese Seiten überhaupt keinem wie auch immer gearteten Zweck,
			jedenfalls keinem von dem ich wüsste.
		</section>
		<?php /* ?>
		<section class="copyright">
			Alle bestandteile dieser Seite unterliegen der
			<span class="italic">GNU General Public License (GNU GPLv3)</span>
			und sind daher frei kopierbar.
		</section>
		*/ ?>
		<section class="signature">
			Viele Grüße und ein schönes Leben,<br />
			Sascha 'SirFoomy' Schneider
		</section>
	</article>
</div>
<div class="clear"></div>
<?php include 'inc/html_foot.phtml'; ?>