<div id="countdown">

	<table style="margin: 50px auto;">
		<tr>
			<td colspan="6" style="text-align: center;"><h3>Countdown to a Better Life</h3></td>
		</tr>
		<tr>
			<th>month</th>
			<th>week</th>
			<th>days</th>
			<th>hours</th>
			<th>minutes</th>
			<th>seconds</th>
		</tr>
		<tr>
			<?php foreach ($this->timeElements as $key => $tm): ?>
				<td class="<?php echo $this->css[$key]; ?>"><?php echo $tm; ?></td>
			<?php endforeach; ?>
		</tr>
	</table>
</div>
<script type="text/javascript">
/* <![CDATA[ */
$(document).ready(function () {
	var months, weeks, days, hours, minutes, seconds;

	window.setInterval(function () {
		seconds = parseInt($('.is_seconds').html(), 10);

		if (seconds > 0) {
			$('.is_seconds').html(--seconds);
		}
		else {
			$('.is_seconds').html(59);
			minutes = parseInt($('.is_minutes').html(), 10);

			if (minutes > 0) {
				$('.is_minutes').html(--minutes);
			}
			else {
				$('.is_minutes').html(59);
				hours = parseInt($('.is_hours').html(), 10);

				if (hours > 0) {
					$('.is_hours').html(--hours);
				}
				else {
					$('.is_hours').html(23);
					days = parseInt($('.is_days').html(), 10);

					if (days > 0) {
						$('.is_days').html(--days);
					}
				}
			}
		}


	}, 1000);
});
/* ]]> */
</script>