<blockquote class="elminster">
	Das leben hat keine Bedeutung, außer der welche wir ihm geben.<br>
	Ich wünschte nur mehr von würden dies auch tun.
	<div class="cited">-- Elminster von Schattental</div>
</blockquote>
<blockquote class="signal">
	Und nicht vergessen:<br>
	"Das Signal kann man nicht aufhalten. Das Signal kann man niemals aufhalten!"
</blockquote>
<div id="jokelink">
	<a href="/joke/">Ein Witz!</a><br>
</div>