<div id="joke">
	<h2>The Irish</h2>
	<p>
		A man stumbles up to the only other patron in the bar and
		asks if he could buy him a drink.
	</p>
	<p class="indent"><em class="secondMan">"Why of course"</em>, comes the reply.</p>
	<p>
		The first man then asks, <em class="firstMan">"Where are you from?"</em>
	</p>
	<p class="indent">
		<em class="secondMan">"I'm from Ireland"</em>, replies the second man.
	</p>
	<p>
		The first man responds,
		<em class="firstMan">
			"You don't say. I'm from Ireland too!
			Let's have another round to Ireland."
		</em>
	</p>
	<p class="indent">
		<em class="secondMan">"Of course"</em>, replies the second man, and they both
		pour back their drinks.
	</p>
	<p>
		Curious, the first man then asks,
		<em class="firstMan">"Where in Ireland are you from?"</em>
	</p>
	<p class="indent"><em class="secondMan">"Dublin"</em>, comes the reply.</p>
	<p class="indent">
		<em class="firstMan">"I can't believe it"</em>, says the first man.
		<em class="firstMan">"I'm from Dublin too!"</em>
	</p>
	<p class="indent">
		<em class="firstMan">"Let's have another drink to Dublin!"</em> The men both
		continue drinking.
	</p>
	<p>
		Curiosity strikes again and the first man asks,
		<em class="firstMan">"What school did you go to?"</em>
	</p>
	<p class="indent">
		<em class="secondMan">"St. Mary's"</em>, replied the second man.
		<em class="secondMan">"I graduated in '62."</em>
	</p>
	<p class="indent">
		<em class="firstMan">"This is unbelievable"</em>, the first man says.
		<em class="firstMan">"I went to St. Mary's and I graduated in '62, too!"</em>
	</p>
	<p class="pointe">
		About that time, in comes one of the regulars and sits down at the bar.
		<em class="regular">"What's been going on?"</em> he asks the bartender.
		<em class="bartender">"Nothing much"</em>, replies the bartender.
		<em class="bartender">"The O'Mally twins are getting drunk again."</em>
	</p>
</div>
<div id="backlink">
	<a href="/">« back</a>
</div>