<?php require_once 'header.phtml'; ?>
<?php require_once 'main-navigation.phtml'; ?>

  <div id="content">
    <article id="curriculum-vitae">
      <h2>Lebenslauf</h2>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-3">
          <div class="bubble green r100">
            <p class="two-lines">
              * 07.06.1977<br>
              Pirmasens
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-4">
          <div class="bubble green r100">
            <p class="two-lines">
              1984 - 1988<br>
              Grundschule
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-3">
          <div class="bubble blue o75x50" style="float: left;">
            <p>
              Hauptschul-<br>
              abschluss
            </p>
          </div>
          <div class="bubble green r100" style="margin-top: 40px;">
            <p class="two-lines">
              1988 - 1993<br>
              Hauptschule
            </p>
          </div>
        </div>
        <div class="col-sm-2">
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-4">
          <div class="bubble green r115">
            <p class="three-lines">
              1993 - 1997<br>
              Ausbildung<br>
              KFZ-Mechaniker
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-3">
          <div class="bubble green r115">
            <p class="three-lines">
              1999-2000<br>
              Grundwehrdienst<br>
              Bundeswehr
            </p>
          </div>
        </div>
        <div class="col-sm-2 col-sm-offset-2">
          <div class="bubble green r125">
            <p class="four-lines">
              1997 - 1999<br>
              Höhrere<br>
              Berufsfachschule<br>
              für Informatik
            </p>
          </div>
        </div>
        <div class="col-sm-2">
          <div class="bubble green r125">
            <p class="four-lines">
              1998 - 2000<br>
              Gewerbeanmeld.<br>
              Handel mit<br>
              Hard- & Software
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-1">
          <div class="bubble green r125">
            <p class="three-lines">
              2000 - 2001<br>
              Lehrgang<br>
              Lotus Notes/Domino
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-3">
          <div class="bubble green r175">
            <p  class="five-lines">
              2002 - 2005<br>
              Ausbildung<br>
              Fachinformatiker<br>
              fachr. Anwendungs-<br>
              entwicklung
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-4">
          <div class="bubble green r200">
            <p class="three-lines">
              2005 - 2006<br>
              ANW GmbH & Co. KG<br>
              Junior Softwareentwickler
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-3">
          <div class="bubble green r200">
            <p class="three-lines">
              2005 - 2006<br>
              Schneemenschen GmbH<br>
              Junior Softwareentwickler
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-4">
          <div class="bubble green r200">
            <p class="three-lines">
              2008 - 2009<br>
              ANW GmbH & Co. KG<br>
              Junior Softwareentwickler
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-2">
          <div class="bubble green r200">
            <p class="three-lines">
              2009 - 2010<br>
              von Affenfels GmbH<br>
              Junior Softwareentwickler
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-4">
          <div class="bubble green r200">
            <p class="three-lines">
              2011<br>
              KWICK! Community<br>
              GmbH & Co. KG<br>
              Softwareentwickler
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-2">
          <div class="bubble green r200">
            <p class="three-lines">
              2011 - 2014<br>
              NetsDirekt GmbH<br>
              Softwareentwickler
            </p>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-2 col-sm-offset-4">
          <div class="bubble green r200">
            <p class="three-lines">
              2015<br>
              ANW GmbH & Co. KG<br>
              Softwareentwickler
            </p>
          </div>
        </div>
      </div>
    </article>
  </div>

<?php require_once 'footer.phtml'; ?>