<?php require_once 'header.phtml'; ?>

<article id="curriculum-vitae">
  <h2>Lebenslauf</h2>

  <blockquote class="elminster">
    Das Leben hat keine Bedeutung, außer der welche wir ihm geben.<br>
    Ich wünschte nur mehr von euch würden dies auch tun.
    <div class="author">-- Elminster von Schattental</div>
  </blockquote>

  <div class="row">
    <div class="col-sm-2 col-sm-offset-3">
      <div class="birth bubble bubble-green">
        <p>
          * 07.06.1977<br>
          Pirmasens
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 col-sm-offset-4">
      <div class="elementary-school bubble bubble-green">
        <p>
          1984 - 1988<br>
          Grundschule
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 col-sm-offset-3">
      <div class="high-school bubble bubble-green">
        <p>
          1988 - 1993<br>
          Hauptschule
        </p>
      </div>
      <div class="high-school-grade bubble bubble-blue">
        <p>
          Hauptschul-<br>
          abschluss
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 col-sm-offset-4">
      <div class="motor-mechanic-apprenticeship bubble bubble-green">
        <p>
          1993 - 1997<br>
          Ausbildung<br>
          KFZ-Mechaniker
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 col-sm-offset-3">
      <div class="basic-military-service bubble bubble-green">
        <p>
          1999-2000<br>
          Grundwehrdienst<br>
          Bundeswehr
        </p>
      </div>
    </div>
    <div class="col-sm-2 col-sm-offset-2">
      <div class="higher-vocational-college bubble bubble-green">
        <p>
          1997 - 1999<br>
          Höhrere<br>
          Berufsfachschule<br>
          für Informatik
        </p>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="hardware-trade bubble bubble-green">
        <p>
          1998 - 2000<br>
          Gewerbeanmeld.<br>
          Handel mit<br>
          Hard- & Software
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
      <div class="lotus-notes bubble bubble-green">
        <p>
          2000 - 2001<br>
          Lehrgang<br>
          Lotus Notes u.<br>
          Domino
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="it-specialist-apprenticeship bubble bubble-green">
        <p>
          2002 - 2005<br>
          Ausbildung<br>
          Fachinformatiker<br>
          fachr. Anwendungs-<br>
          entwicklung
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="anw-2005 bubble bubble-green">
        <p>
          2005 - 2006<br>
          ANW GmbH & Co. KG<br>
          Junior Softwareentwickler
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="schneemenschen bubble bubble-green">
        <p>
          2006 - 2008<br>
          Schneemenschen GmbH<br>
          Junior Softwareentwickler
        </p>
      </div>
      <div class="staedte-reisen bubble bubble-blue">
        <a href="http://www.staedte-reisen.de/" target="_blank">staedte-reisen.de</a>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="anw-2008 bubble bubble-green">
        <p>
          2008 - 2009<br>
          ANW GmbH & Co. KG<br>
          Junior Softwareentwickler
        </p>
      </div>
      <div class="trackhints bubble bubble-blue">
        <p>trackhints.com</p>
      </div>

    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="von-affenfels bubble bubble-green">
        <p>
          2009 - 2010<br>
          von Affenfels GmbH<br>
          Junior Softwareentwickler
        </p>
      </div>
      <div class="magnus bubble bubble-blue">
        <p>magnus.de</p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="kwick bubble bubble-green">
        <p>
          2011<br>
          KWICK! Community<br>
          GmbH & Co. KG<br>
          Softwareentwickler
        </p>
      </div>
      <div class="kwick-site bubble bubble-blue">
        <p>
          <a href="http://www.kwick.de/" target="_blank">kwick.de</a>
        </p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="netsdirekt bubble bubble-green">
        <p>
          2011 - 2014<br>
          NetsDirekt GmbH<br>
          Softwareentwickler
        </p>
      </div>
      <div class="weingut-wechsler bubble bubble-blue">
        <p><a href="http://www.weingut-wechsler.de/home/" target="_blank">Weingut Wechsler</a></p>
      </div>
      <div class="packaging bubble bubble-blue">
        <p><a href="http://www.4packaging.de/de/home.html" target="_blank">4packaging</a></p>
      </div>
      <div class="drv-hessen bubble bubble-blue">
        <p><a href="https://www.ausbildung-drv-hessen.de/" target="_blank">DRV Hessen</a></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-3 col-sm-offset-4">
      <div class="anw-2015 bubble bubble-green">
        <p>
          2015<br>
          ANW GmbH & Co. KG<br>
          Softwareentwickler
        </p>
      </div>
      <div class="highend bubble bubble-blue">
        <p><a href="https://www.highend.de/" target="_blank">highend.de</a></p>
      </div>
      <div class="wimip bubble bubble-blue">
        <p><a href="http://www.wieistmeineip.de/" target="_blank">wieistmeineip.de</a></p>
      </div>
      <div class="cobi bubble bubble-blue">
        <p>
          <a href="http://dsl-speedtest.computerbild.de/" target="_blank">Computerbild<br>DSL-Speedtest</a>
        </p>
      </div>
    </div>
  </div>
</article>

<?php require_once 'footer.phtml'; ?>