    <footer>
      <div class="row">
        <div class="footer-quote col-sm-8">
          Psst... Gerüchten zufolge wurde hier in der Gegend ein Footer gesehen.<br>
          Belohnung: 3 Tassen Kaffee für sachdienliche Hinweise die zur Ergreifung führen.
        </div>
        <div class="footer-links col-sm-4">
          :: <a href="javascript:;">Impressum</a>
          :: <a href="javascript:;">Kontakt</a> ::<br>
          :: <a href="http://www.spiegel.de/netzwelt/politik/0,1518,375970,00.html" target="_blank">Disclaimer</a>
          :: <a href="javascript:;">FAQ</a> ::<br>
        </div>
      </div>
      <div class="geek-code-block row">
        <a href="http://www.geekcode.com/" target="_blank">GCS
          d-- s-:+ a C++$>(+++) UL P+ L+ E? W++ N+ o? K? w !O !M V? PS+ PE Y+
          PGP+ t++>(+++) 5+ X+ R !tv b+ DI D G e-- h r- y?</a>
      </div>
    </footer>
  </div>
</div>
<?php require_once 'html-footer.phtml'; ?>