<?php require_once 'header.phtml'; ?>
<article id="gallery-overview">
	<div class="gallery is_gallery" data-galid="gal1">
		<div class="gallery-cover">
			<img class="cover-thumbnail rot-left is_rotLeft-gal1" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="" style="z-index:5">
			<img class="cover-thumbnail rot-right is_rotRight-gal1" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="" style="z-index:4">
			<img class="cover-thumbnail" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="" style="z-index:3">
		</div>
		<div class="gallery-title">
			Albumtitel
		</div>
	</div>
	<div class="gallery is_gallery" data-galid="gal2">
		<div class="gallery-cover">
			<img class="cover-thumbnail rot-left is_rotLeft-gal2" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="" style="z-index:5">
			<img class="cover-thumbnail rot-right is_rotRight-gal2" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="" style="z-index:4">
			<img class="cover-thumbnail" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="" style="z-index:3">
		</div>
		<div class="gallery-title">
			Albumtitel
		</div>
	</div>
	<div class="gallery is_gallery" data-galid="gal3">
		<div class="gallery-cover">
			<img class="cover-thumbnail rot-left is_rotLeft-gal3" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="" style="z-index:5">
			<img class="cover-thumbnail rot-right is_rotRight-gal3" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="" style="z-index:4">
			<img class="cover-thumbnail" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="" style="z-index:3">
		</div>
		<div class="gallery-title">
			Albumtitel
		</div>
	</div>
</article>
<?php require_once 'footer.phtml'; ?>
