<?php require_once 'header.phtml'; ?>
<?php require_once 'main-navigation.phtml'; ?>

<div id="content">
  <div id="home">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-1">
        <blockquote class="elminster">
          Das leben hat keine Bedeutung, außer der welche wir ihm geben.<br>
          Ich wünschte nur mehr von würden dies auch tun.
          <div class="quote-author">-- Elminster von Schattental</div>
        </blockquote>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-7 col-sm-offset-2">
        <blockquote class="mr-universe">
          Das Signal kann man nicht aufhalten. Das Signal kann man niemals aufhalten!
          <div class="quote-author">-- Mr. Universe</div>
        </blockquote>
      </div>
    </div>
  </div>
</div>

<?php require_once 'footer.phtml'; ?>
