<?php require_once 'header.phtml'; ?>

<div id="home">
  <div class="row">
    <div class="col-sm-12">
      <blockquote>
        <div class="first-part">
          Fahre fort, übe nicht allein die Kunst, sondern dringe in ihr Inneres; Sie verdient es,<br>
          denn nur die Kunst und die Wissenschaft erhöhen den Menschen bis zur Gottheit.
        </div>
        <div class="second-part"></div>
        <div class="author">-- Ludwig van Beethoven</div>
      </blockquote>
    </div>
  </div>
</div>
<script>
  window.setTimeout(function () {
    $('blockquote .first-part').fadeIn(2000, function () {
      window.setTimeout(function () {
        $('blockquote .second-part').fadeIn(2000, function () {
          window.setTimeout(function () {
            $('blockquote .author').fadeIn(2000);
          }, 1000);
        });
      }, 1000);
    });
  }, 750);
</script>

<?php require_once 'footer.phtml'; ?>
