<?php require_once 'header.phtml'; ?>

<div id="home">
  <div class="row">
    <div class="col-sm-12">
      <blockquote>
        <div class="first-part">The best way to predict the future...</div>
        <div class="second-part">... is to invent it.</div>
        <div class="author">-- Alan Kay</div>
      </blockquote>
    </div>
  </div>
</div>
<script>
  window.setTimeout(function () {
    $('blockquote .first-part').fadeIn(2000, function () {
      window.setTimeout(function () {
        $('blockquote .second-part').fadeIn(2000, function () {
          window.setTimeout(function () {
            $('blockquote .author').fadeIn(2000);
          }, 1000);
        });
      }, 1000);
    });
  }, 750);
</script>

<?php require_once 'footer.phtml'; ?>
