<?php require_once 'header.phtml'; ?>

<article id="impress">
  <h3>Diese Seiten wurden verbrochen von</h3>
  <address>
    Sascha Schneider<br>
    foomy.code@arcor.de
  </address>
  <p class="col-sm-6">
    SirFoomys Welt ist eine private Homepage und dient keinem geschäftsmäßigen Zweck.
    Genau betrachtet dienen diese Seiten eigentlich überhaupt keinem höheren Zweck,
    jedenfalls keinem von dem ich wüsste.
  </p>
  <p class="col-sm-12 small">
    (Selbstdarstellung und geistiger Exhibitionismus sind keine Verwendungszwecke.)
  </p>
</article>

<?php require_once 'footer.phtml'; ?>