<?php require_once 'html-header.phtml'; ?>
<div id="sitewrapper">
  <div id="pagewrapper" class="row">
    <?php require_once 'header.phtml'; ?>
    <?php require_once 'main-navigation.phtml'; ?>

    <div id="content">
      <article id="impress">
        <h3>Diese Seiten wurden verbrochen von</h3>
        <address>
          Sascha Schneider<br>
          foomy.code@arcor.de
        </address>
        <p class="col-sm-6">
          SirFoomys Welt ist eine private Homepage und dient keinem geschäftsmäßigen Zweck.
          Genau betrachtet dienen diese Seiten eigentlich überhaupt keinem höheren Zweck,
          jedenfalls keinem von dem ich wüsste.
        </p>
      </article>
    </div>

    <?php require_once 'footer.phtml'; ?>
  </div>
</div>
<?php require_once 'html-footer.phtml'; ?>
