<nav id="main" class="navbar navbar-default col-sm-12">
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
      <li><a href="javascript:;">Link 1</a></li>
      <li><a href="javascript:;">Link 2</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown 1<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="javascript:;">Link 3</a></li>
          <li><a href="javascript:;">Link 4</a></li>
        </ul>
      </li>
      <li><a href="javascript:;">Link 5</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown 2<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="javascript:;">Link 6</a></li>
          <li><a href="javascript:;">Link7</a></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
<div class="clearfix"></div>
