<?php require_once 'header.phtml'; ?>
<?php require_once 'main-navigation.phtml'; ?>

<div id="content">
  <article id="privacy">
    <h2>Datenschutzhinweise</h2>

    <section>
      <h3>Einleitung</h3>
      <p>
        Da ich persönlich Datenschutz für sehr wichtig halte und auch für diesbezügliche Transparenz stehe will ich
        im Folgenden darauf eingehen wir auf SirFoomys Welt mit Daten umgegangen wird.
      </p>
    </section>
    <section>
      <h3>Kontakformular</h3>
      <p>
        Das Kontaktformular verschickt eine E-Mail mit dem von Ihnen eingegeben Inhalt an mich. Diese E-Mails werden
        nach Ende der Korrespondenz gelöscht. Ansonsten werden dazu keine Daten gespeichert.
      </p>
    </section>
    <section>
      <h3>Tracker-Tools</h3>
      <p>
        Für SirFoomys Welt sind keinerlei Tracker-Tools im Einsatz (Bspw.: Google Analytics, Piwik, eTracker o.ä.).
      </p>
    </section>
    <section>
      <h3>Cookies</h3>
      <p>
        Auf dieser Webseite werden keine Cookies verwendet.
      </p>
    </section>
    <section>
      <h3>Serverdaten</h3>
      <p>
        Beim Verbindungsaufbau Ihres Browsers mit dem Server auf dem SirFoomys Welt läuft, werden durch den Server
        Log-Dateien geschrieben. Diese werden zum Erkennen und Beheben von Fehlern genutzt. Sie enthalten keine
        personenbezogenen Daten und es werden auch keine Daten gespeichert durch die Rückschlüsse auf
        personenbezogene Daten möglich sind (Bspw.: IP-Adressen).
      </p>
    </section>

    <p class="complimentary-close">
      Stuttgart, 30. September 2015<br>
      Sascha Schneider<br>
      <span class="small">(Seiteninhaber)</span>
    </p>
  </article>
</div>

<?php require_once 'footer.phtml'; ?>