<div class="pagination bottom">
	<div class="inner">
		<div>
			<span class="first"><img src="/img/icons/resultset_first_mc.png" alt="|&lt;" title="Zur ersten Seite springen." /></span>
			<span class="prev"><img src="/img/icons/resultset_previous_mc.png" alt="&lt;" title="Zurückblättern" /></span>
		</div>
		<ul class="pagenumbers">
				<li><a href="javascript:;" class="page">1</a></li>
				<li>2</li>
				<li><a href="javascript:;" class="page">3</a></li>
				<li><a href="javascript:;" class="page">4</a></li>
				<li><a href="javascript:;" class="page">5</a></li>
		</ul>
		<div>
			<span class="next"><img src="/img/icons/resultset_next_mc.png" alt="&gt;" title="Vorblättern" /></span>
			<span class="last"><img src="/img/icons/resultset_last_mc.png" alt="&gt;|" title="Zur letzten Seite springen." /></span>
		</div>
	</div>
	<div class="clear"></div>
</div>