<!DOCTYPE html>
<html lang="de">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

	<title>SirFoomys Welt</title>

	<link href="css/skin-default.css" media="screen" rel="stylesheet" type="text/css" >

	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/RunApp.js"></script>
</head>

<body>
<div id="sitewrapper">
	<div id="overlay" class="hidden is_overlay">&nbsp;</div>

	<div id="pagewrapper">
		<header id="header">
			<div class="headerTop">
				<img class="logo" src="/img/logo.png" alt="" title="" />
			</div>
			<div class="infobar"></div>
		</header>
