<div id="motto">
  Das Leben hat keine Bedeutung außer der, welche wir ihm geben.<br />
  Ich wünschte, ein paar mehr von euch würden das auch tun.<br />
  <div class="fett">Elminster von Schattental</div>
</div>
<hr style="width:100%; margin-bottom:30px" />

<h3>Was ist das hier?</h3>
Eigentlich nur eine priv. Homepage!

<h3>Wann geht's los?</h3>
Ich hoffe mal in diesem Leben noch. Immerhin bastel ich schon seit 2004 an
dieser Seite. Mehrfach neu angefangen, weil ich aus verschiedensten Gründen
alles wieder über den Haufen geworfen hab. Das kommt davon wenn man schneller
dazulernt als die eigenen Projekte gedeihen.

<h3>Fehlt hier nicht noch was?</h3>
So ziemlich alles würd ich sagen. Da wären zum Bleistift:
<div id="fehlliste">
  <ul style="margin:10px;">
    <li>
      <div class="fett">Die Bildergalerie</div>
      Meine Version von Flickr.com mit nur einem (Premium)user!    
    </li>
    <li>
      <div class="fett"><a href="/blog/">Ein Weblog</a></div>
      cat /dev/brain &gt; /blog - Mehr gibts dazu eigentlich auch nicht zu sagen.
    </li>
    <li>
      <div class="fett">"Möchten Sie mehr wissen?"</div>
      Der Klugschseißer in mir will auch seinen Platz.
    </li>
    <li>
      <div class="fett">GW-Tool</div>
      Damit da mal Ordnung in die Zettel kommt. Hier wird es dann
      Charakter- und Heldenbögen geben, und einiges mehr.
    </li>
    <li>
      <div class="fett">Panoptikum</div>
      Sammlung verschiedener Kuriositäten.
    </li>
  </ul>
</div>
