<?php
/**
 * phx_puzzle.de.tmpl.php, foomy.net-test
 * 04.07.2009
 *  
 * @author Sascha Schneider <foomy.code@arcor.de>
 * @copyright (c) 2009 by Sascha Schneider
 */
?>
HalloLindaNylonNunwirdunserTrackerschon3JahrealtEsgabzwarkleinereProblemeaberjetztläufterwirklichsuperMerlindergroßeZaubereristunswohlgutmütiggesonnenObAndiTomatooderNancyDevilobnunOssiWessioderAusländerjederversuchtsichdiebestenTorrentszukrallenSeiesMusikvomTenorDiStefanoeineDokuvomseltenenMaitaiHaioderauchriesigeTorrentsüber25GBdiewirModsabsegnenmüssenDieseltsamstenTorrentswerdenhiergeupptNurzurInfoobartiggeseedetwirdkönnenwirjederzeitüberprüfenWerSLbetreibtbekommtBesuchvomSensenmannlerntvonunsdasFliegenundzwarvomTrackerAberkeineSorgeichbineinganzbraverundmeineRatioistimgrünenBereichDeinAbrAndyvonBlödsinnKleinerAnhangManyThanksanunserenSysOpohnedendasallesnichtmöglichwäre 