<?php echo $this->doctype() . PHP_EOL; ?>
<html lang="de">
<head>
<?php
	echo $this->headMeta()->toString("\t") . PHP_EOL;
	echo $this->headTitle()->toString("\t") . PHP_EOL;

	$this->loadSkin($this->skin);
	echo $this->headLink()->toString("\t") . PHP_EOL;

	echo $this->headScript()->toString("\t") . PHP_EOL;
?>

	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/RunApp.js"></script>
</head>

<body>
<div id="sitewrapper">
	<div id="overlay" class="hidden is_overlay">&nbsp;</div>

	<div id="pagewrapper">
		<header id="header">
			<div class="headerTop">
				<a href="/"><img class="logo" src="/img/logo.png" alt="" title=""></a>
			</div>
			<div class="infobar"></div>
		</header>

		<?php echo $this->partial('_sublayouts/' . $this->layout . '.phtml'); ?>

		<footer id="footer">
			<div class="mainbox">
				<div class="links">
					.:: <a href="/impress/">Impressum</a> |
					<a href="mailto:foomy.code@arcor.de">Kontakt</a> |
					<!--a href="/faq/"-->FAQ<!--/a--> |
					<a href="http://www.spiegel.de/netzwelt/politik/0,1518,375970,00.html" rel="extern">Disclaimer</a>
					::.
				</div>
				<div class="copyright">Designed &amp; programmed by Sascha Schneider</div>
				<p class="geekCode"><a href="http://www.geekcode.com/" rel="extern">GCS d-- s-:+ a C++$>(+++) UL P+ L+ E? W++ N+ o? K? w !O !M V? PS+ PE Y+ PGP+ t++>(+++) 5+ X+ R !tv b+ DI D G e-- h r- y?</a></p>
			</div>
			<div class="microbanner">
				<img src="/img/microbanner/valid_html5.png" alt="Valid HTML5!" title="Valid HTML5!"><br>
				<img src="/img/microbanner/valid_css3.png" alt="Valid CSS3!" title="Valid CSS3!"><br>
				<img src="/img/microbanner/zend_framework.gif" alt="Powerd by Zend Framework!" title="Powerd by Zend Framework"><br>
				<img src="/img/microbanner/jquery.png" alt="jQuery in Action!" title="jQuery in Action!">
			</div>
		</footer>
		<?php if (APPLICATION_ENV !== 'production'): ?>
			<div id="gotoWf">
				<a href="/workfiles/">Goto workfiles »</a>
			</div>
		<?php endif; ?>
	</div>

	<div id="lightbox" class="lightbox hidden is_layer">
		<div class="control"><button class="is_layer_close">[x]</button></div>
		<div class="content"></div>
	</div>
</div>


</body>
</html>
