<?php echo $this->doctype(); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('SirFoomys ' . $this->translate('Welt'))->setSeparator(' - ')->setAutoEscape(false) . PHP_EOL; ?>
  <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge') . PHP_EOL; ?>

  <?php
  $this->loadSkin();
  echo $this->headLink() . "\n\n";

  $this->loadScripts();
  echo $this->headScript() . PHP_EOL;
  ?>
</head>
<body>
<div id="sitewrapper">
  <div id="pagewrapper" class="container">
    <header>
      <img src="/skins/default/img/logo.png" alt="SirFoomys Welt">
    </header>

    <nav id="main" class="navbar navbar-default col-sm-12">
      <div class="navbar-collapse collapse">
        <?php echo $this->navigation('navigation')->menu()->setPartial('partial/menu')->render(); ?>
      </div>
    </nav>
    <div class="clearfix"></div>

    <div id="content">
      <?php echo $this->content; ?>
    </div>

    <footer>
      <div class="row">
        <div class="footer-quote col-sm-6 col-sm-offset-1">
          Psst... Gerüchten zufolge wurde hier in der Gegend ein Footer gesehen.<br>
          Belohnung: 3 Tassen Kaffee für sachdienliche Hinweise die zur Ergreifung führen.
        </div>
        <div class="footer-links col-sm-5">
          :: <a href="/contact/"><?php echo $this->translate('Kontakt'); ?></a>
          :: <a href="/legal-notice/"><?php echo $this->translate('Impressum'); ?></a> ::<br>
          :: <a href="/privacy/"><?php echo $this->translate('Datenschutz'); ?></a>
          :: <a href="http://www.spiegel.de/netzwelt/politik/0,1518,375970,00.html"
                target="_blank"><?php echo $this->translate('Disclaimer'); ?></a>
          :: <a href="/faq/"><?php echo $this->translate('FAQ'); ?></a> ::<br>
        </div>
      </div>
      <div class="geek-code-block row">
        <a href="http://www.geekcode.com/" target="_blank">GCS
          d-- s-:+ a C++$>(+++) UL P+ L+ E? W++ N+ o? K? w !O !M V? PS+ PE Y+
          PGP+ t++>(+++) 5+ X+ R !tv b+ DI D G e-- h r- y?</a>
      </div>
    </footer>
  </div>
</div>
</body>
</html>
