<?php echo $this->doctype(); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('SirFoomys ' . $this->translate('Welt'))->setSeparator(' - ')->setAutoEscape(false); ?>
  <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

  <?php
    $this->loadSkin();
    echo $this->headLink() . PHP_EOL;
  ?>

</head>
<body>
<div id="sitewrapper">
  <div id="pagewrapper" class="container">
    <header>
      <img src="/skins/default/img/logo.png" alt="SirFoomys Welt">
    </header>

    <nav id="main" class="navbar navbar-default col-sm-12">
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="javascript:;">Link 1</a></li>
          <li><a href="javascript:;">Link 2</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown 1<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="javascript:;">Link 3</a></li>
              <li><a href="javascript:;">Link 4</a></li>
            </ul>
          </li>
          <li><a href="javascript:;">Link 5</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown 2<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="javascript:;">Link 6</a></li>
              <li><a href="javascript:;">Link7</a></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
    <div class="clearfix"></div>

    <div id="content">
      <?php echo $this->content; ?>
    </div>

    <footer>
      <div class="row">
        <div class="footer-quote col-sm-8">
          Psst... Gerüchten zufolge wurde hier in der Gegend ein Footer gesehen.<br>
          Belohnung: 3 Tassen Kaffee für sachdienliche Hinweise die zur Ergreifung führen.
        </div>
        <div class="footer-links col-sm-4">
          :: <a href="javascript:;">Impressum</a>
          :: <a href="javascript:;">Kontakt</a> ::<br>
          :: <a href="http://www.spiegel.de/netzwelt/politik/0,1518,375970,00.html" target="_blank">Disclaimer</a>
          :: <a href="javascript:;">FAQ</a> ::<br>
        </div>
      </div>
      <div class="geek-code-block row">
        <a href="http://www.geekcode.com/" target="_blank">GCS
          d-- s-:+ a C++$>(+++) UL P+ L+ E? W++ N+ o? K? w !O !M V? PS+ PE Y+
          PGP+ t++>(+++) 5+ X+ R !tv b+ DI D G e-- h r- y?</a>
      </div>
    </footer>
  </div>
</div>
<?php echo $this->inlineScript() ?>
</body>
</html>
