<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="twoColRight">
	<article class="is_content">
		<section id="articlelist">
			<?php include 'inc/pagination-top.phtml'; ?>
			<div class="article">
				<div class="head">
					<div class="date">Mi, 15.02.2012</div>
					<div class="headline head3"><a href="javascript:;">Bikinis strahlender Tag</a></div>
					<div class="author">Author: Sascha Schneider</div>
				</div>
				<div class="body">
					Am 1. März 2004 ist der 50. Jahrestag der Detonation der
					US-Wasserstoffbombe "Bravo" auf dem Bikini-Atoll. Zwischen 1946 und
					1958 testeten die USA auf dem Bikini- und dem benachbarten
					Eniwetok-Atoll annähernd 70 Atom- und Wasserstoffbomben. Der
					verheerendste Test fand am 1. März 1954 statt, bei dem durch die
					Detonation der Wasserstoffbombe mit dem Code-Namen "Bravo" hunderte
					Insulaner im Pazifik radioaktiv verseucht wurden.
				</div>
				<div class="foot">
					<nav class="articlePreview">
						<ul class="ctrl">
							<li><a href="javascript:;">read</a></li>
							<li><a href="javascript:;">edit</a></li>
							<li><a href="javascript:;">delete</a></li>
						</ul>
					</nav>
					<div class="clear"></div>
				</div>
			</div>
			<div class="article">
				<div class="head">
					<div class="date">Mi, 15.02.2012</div>
					<div class="headline head3"><a href="javascript:;">Kleine Titanen</a></div>
					<div class="author">Author: Sascha Schneider</a></div>
				</div>
				<div class="body">
					Mit der Erfindung der ersten Zahlensysteme hatte der Mensch Verlangen nach
					Rechenhilfen. Im antiken Griechenland war rechnen eines Normalbürgers sogar
					unwürdig, zumindest was das Zahlenrechnen, also einfache Arithmetik betraf. Es
					wurde den Sklaven überlassen. Die wohl älteste Rechenhilfe ist das Rechenbrett,
					eine Steintafel mit aufgetragenen Linien, auf denen Zahlenmarken oder Steinchen
					verschoben wurden. Die Römer nannten diese Steinchen später 'calculi'
					(Die heutigen Wörter kalkulieren oder Kalkül leiten sich davon ab.) die ganze
					Rechenhilfe wurde 'Abakus' (von abax = lat. Tafel) genannt.
				</div>
				<div class="foot">
					<nav class="articlePreview">
						<ul class="ctrl">
							<li><a href="javascript:;">read</a></li>
							<li><a href="javascript:;">edit</a></li>
							<li><a href="javascript:;">delete</a></li>
						</ul>
					</nav>
					<div class="clear"></div>
				</div>
			</div>
			<div class="article last">
				<div class="head">
					<div class="date">Mi, 15.02.2012</div>
					<div class="headline head3"><a href="javascript:;">Migration von Webprojekten auf PHP5</a></div>
					<div class="author">Author: Sascha Schneider</div>
				</div>
				<div class="body">
					Bei einer Umstellung von PHP4 auf PHP5 kann es erforderlich werden, dass ältere
					Webprojekte angepasst werden müssen. PHP5 ermöglicht einen gut wartbaren und
					übersichtlich strukturierten Code. Der Grund hierfür ist das neue Objektmodell,
					das es erlaubt, einen Großteil der im Rahmen der objektorientierten
					Programmierung üblichen Verfahren einzusetzen.
				</div>
				<div class="foot">
					<nav class="articlePreview">
						<ul class="ctrl">
							<li><a href="javascript:;">read</a></li>
							<li><a href="javascript:;">edit</a></li>
							<li><a href="javascript:;">delete</a></li>
						</ul>
					</nav>
					<div class="clear"></div>
				</div>
			</div>
			<?php include 'inc/pagination-bottom.phtml'; ?>
		</section>
	</article>
	<aside class="is_sidebar"></aside>
	<div class="clear"></div>
</div>
<?php include 'inc/html_foot.phtml'; ?>