<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="oneColumn">
	<article class="is_content">
		<div id="gallery">
			<div class="mainview">
				<img src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="">
			</div>
			<div class="thumbnails">
				<img class="thumbnail" src="/img/gallery/b808a9c0-pflanzen/gaensebloemscher.jpg" alt="">
				<img class="thumbnail" src="/img/gallery/b808a9c0-pflanzen/klivie.jpg" alt="">
				<img class="thumbnail" src="/img/gallery/b808a9c0-pflanzen/rose.jpg" alt="">
			</div>
		</div>
	</article>
</div>
<?php include 'inc/html_foot.phtml'; ?>
