<?php include 'inc/html_head.phtml'; ?>
<div id="content" class="oneColumn">
	<article class="is_content">
		<div class="quotebox">
			<textarea class="is_quotearea" rows="1" cols="1">
So long as the universe had a beginning, we could suppose it had a creator. But if the universe is really completely self-contained, having no boundary or edge, it would have neither beginning nor end: it would simply be. What place, then, for a creator?

-- Stephen Hawking (A Brief History of Time)
			</textarea>
		</div>
		<div class="optimizationNote">
			Die folgenden Seiten wurden so optimiert, dass sie in keinem<br />
			mir derzeit bekannten Browser richtig angezeigt werden können.
		</div>
		<div class="entrance">
			:: <a href="/home.php">Enter</a> ::
		</div>
		<div class="funDisclaimer">
			<div class="warn">*** Warnung! *** Warnung! *** Warnung ***</div>
			Das Lesen dieser Seiten kann zu Schizophrenie, Realitätsverlust und
			anderen psychischen Störungen führen. Der Autor übernimmt in keinster
			Weise Haftung für irgendwelche geistigen oder köperlichen Schäden.
			<div class="warn">*** Warnung! *** Warnung! *** Warnung ***</div>
			</div>
	</article>
</div>
<?php include 'inc/html_foot.phtml'; ?>
