<?php if ( $this->pageCount): ?>
  <div class="pagination-control">
    <!-- "Vorherige Seite"-Link -->
    <?php if ( isset($this->previous) ): ?>
      <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">&lt; Zurück&nbsp;&nbsp;</a> |
    <?php else: ?>
      <span class="disabled">&lt; Zurück&nbsp;&nbsp;</span> 
    <?php endif; ?>

    <!-- "Anzahl Seiten"-Links -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ( $page!=$this->current): ?>
        <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> |
      <?php else: ?>
        <?php echo $page; ?> |
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- "Nächste Seite"-Link -->
    <?php if ( isset($this->next) ): ?>
      <a href="<?php echo $this->url(array('page' => $this->next)); ?>">&nbsp;&nbsp;Vor &gt;</a>
    <?php else: ?>
      <span class="disabled">&nbsp;&nbsp;Vor &gt;</span>
    <?php endif; ?>
  </div>
<?php endif; ?>
