<div id="bastelcontent">
  <ul>
    <li><a href="/bastel/paginator/">Zend_Paginator</a></li>
    <li><a href="/bastel/gen-data-array/">Testdaten Generator</a></li>
    <li><a href="/bastel/validations/">HTML Validierungstests</a></li>
    <li><a href="/bastel/nice-checkboxes/">Kuhle Checkboxen</a></li>
    <li><a href="/bastel/own-view-helper/">Eigene View Helfer</a></li>
    <li><a href="/bastel/lermoos-bilder/">Auswahl der Bilder aus Lermoos</a></li>
  </ul>
</div>
