<?php if ( count($this->paginator)>0 ): ?>
<p>
  <span class="fett">Schlagzeilen: </span>
  <?php echo $this->paginator->getAbsoluteItemNumber(1); ?> bis
  <?php echo $this->paginator->getAbsoluteItemNumber($this->paginator->getCurrentItemCount()); ?>
   von insgesamt
  <?php echo $this->paginator->getTotalItemCount(); ?>
</p>
<p>
  <ul>
    <?php foreach ($this->paginator as $item): ?>
    <li>
      <?php echo $item['Dachzeile']; ?>:
      <a href="<?php echo $item['URL']; ?>"><?php echo $item['Ueberschrift']; ?></a>
      <span>(<?php echo $item['Rubrik']; ?>, <?php echo $item['Zeit']; ?>)</span>
    </li>
    <?php endforeach; ?>
  </ul>
</p>
<?php echo $this->paginationControl($this->paginator, 'Sliding', 'bastel/_pagination_control.phtml'); ?>
<?php endif; ?>
