<div id="formGenerator">
	<div class="constructionKit">
		<div class="item">
			<input type="radio" id="item_1" name="formelement" value="singleLineField">
			<input type="text" name="x" placeholder="Einzeiliges Textfeld">
			<label for="item_1" class="itemLabel"></label>
		</div>
		<div class="item">
			<input type="radio" id="item_2" name="formelement" value="multiLineField">
			<textarea name="x" placeholder="Mehrzeiliges Textfeld"></textarea>
			<label for="item_2" class="itemLabel"></label>
		</div>
	</div>
</div>