<div class="head1"><?php echo $this->blog->getTitle(); ?></div>
<div class="head2"><?php echo $this->blog->getSubTitle(); ?></div>

<div id="article">
  <div class="headline"><?php echo $this->article->getHeadline(); ?></div>
  <div class="subhead"><?php echo $this->article->getSubhead(); ?></div>
  <p class="abstract"><?php echo $this->article->getAbstract(); ?></p>
  <p class="articletext"><?php echo $this->article->getArticleText(); ?></p>
</div><!-- /blog -->
