<div class="head1"><?php echo $this->blog->getTitle(); ?></div>
<div class="head2"><?php echo $this->blog->getSubTitle(); ?></div>

<?php echo $this->form; ?>

<script type="text/javascript">
/* <![CDATA[ */
  var pCount = 0;

  $(document).ready(function() {
    $('fieldset').removeAttr('id');
    $('#paragraph-label').removeAttr('id');
    $('#paragraph-element').removeAttr('id');
    $('#pSubForm_0-element').addClass('pSubForm');
    

    /**
     * adds a new paragraph subform
     */
    $('#add_paragraph').click(function() {
      npCount = pCount+1; // increment the id count for the new element

      // let's clone something... *mähh* ;o)
      var newSubForm = $('#pSubForm_'+pCount+'-element').clone();
      newSubForm.attr('id', 'pSubForm_'+npCount+'-element');

      var dl = newSubForm.children('fieldset').children();

      // clear label content
      var dt = dl.children('dt');
      dt.html('&nbsp');

      // change id and name of the textarea
      var ta = dl.children('dd').children('textarea');
      ta.attr('id', 'pSubForm_'+npCount+'-paragraph');
      ta.attr('name', 'pSubForm_'+npCount+'[paragraph]');

      // mount the new subform in the DOM
      newSubForm.insertAfter('#pSubForm_'+pCount+'-element');
 
      pCount++;
    });

    $('#reset').click(function() {
      for (i=pCount; i>0; i--) {
        $('#paragraph_'+i+'-label').remove();
        $('#paragraph_'+i+'-element').remove();
        $('#paragraph_0-element').addClass('last-field');
        pCount = 0;
      }
    });
  });
/* ]]> */
</script>
