<form id="quote" action="">
  <div><textarea id="randomquote" rows="" cols=""></textarea></div>
</form>
<div id="optimized">
  Die folgenden Seiten wurden so optimiert, dass sie in keinem<br />
  mir derzeit bekannten Browser richtig angezeigt werden können.
</div>
<p id="entrance">
  :: <a href="/home/">Enter</a> ::
</p>
<p id="fundisclaimer">
  Das Lesen dieser Seiten kann zu Schizophrenie, Realitätsverlust und
  anderen psychischen Störungen führen. Der Autor übernimmt in keinster
  Weise Haftung für irgendwelche geistigen oder köperlichen Schäden.
</p>
<script type="text/javascript">
// <![CDATA[
  var tl=new Array(
    '<?php echo $this->quote->getQuoteText(); ?>',
    ' ',
    '<?php echo $this->quote->getAuthor(); ?>',
    '<?php echo $this->quote->getExtra(); ?>'
  );
  var speed=45;
  var index=0; text_pos=0;
  var str_length=tl[0].length;
  var contents, row;
  type_text();
// ]]>
</script>
