<div id="contact">
  <h2>Kontaktformular</h2>

  <div class="row">
    <p class="col-sm-6">
      Zu erreichen bin ich normalerweise über die im
      <a href="/legal-notice/">Impressum</a> aufgeführte E-Mail Adresse.
    </p>
  </div>

  <div class="row">
    <p class="col-sm-6">
      Für den Fall, dass gerade kein E-Mail-Client zur Hand ist, können Sie
      mir auch gerne über dieses Kontaktformular eine Nachricht zukommen lassen.
    </p>
  </div>

  <div class="row">
    <p class="col-sm-6">
      Wie das im Internert so üblich ist sind die mit * markierten Felder Pflichtfelder.
      In den <a href="/privacy/">Datenschutzhinweisen</a> können Sie nachlesen
      wie mit den von Ihnen gesendeten Daten umgegangen wird.
    </p>
  </div>

  <div class="row">
    <?php if (! $this->showThanks): ?>
    <div class="col-sm-6">
      <?php echo $this->form()->openTag($this->form); ?>
      <fieldset class="data">
        <div class="form-group has-feedback">
          <?php echo $this->formLabel($this->form->get('name')); ?>
          <?php echo $this->formElement($this->form->get('name')); ?><?php /*
          <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>
          <span id="inputSuccess2Status" class="sr-only">(success)</span> */ ?>
         </div>
        <div class="form-group">
          <?php echo $this->formLabel($this->form->get('email')); ?>
          <?php echo $this->formElement($this->form->get('email')); ?>
        </div>
        <div class="form-group">
          <?php echo $this->formLabel($this->form->get('message')); ?>
          <?php echo $this->formElement($this->form->get('message')); ?>
        </div>
      </fieldset>
      <fieldset class="controls">
        <ul>
          <li><?php echo $this->formElement($this->form->get('submit')); ?></li>
          <li><?php echo $this->formElement($this->form->get('cancel')); ?></li>
        </ul>
      </fieldset>
      <?php echo $this->form()->closeTag(); ?>
    </div>
    <?php else: ?>
    <div class="col-sm-6">
      <p class="thanks">
        Vielen Dank für Ihre Nachricht. Ich werde mich so schnell wie es mir möglich um Ihr Anliegen kümmern.
      </p>
    </div>
    <?php endif; ?>
  </div>
</div>
