<div id="home">
  <div class="row">
    <div class="col-sm-12">
      <blockquote>
        <div class="first-part">
          Fahre fort, übe nicht allein die Kunst, sondern dringe in ihr Inneres; Sie verdient es,<br>
          denn nur die Kunst und die Wissenschaft erhöhen den Menschen bis zur Gottheit.
        </div>
        <div class="second-part"></div>
        <div class="author">-- Ludwig van Beethoven</div>
      </blockquote>
    </div>
  </div>
</div>