<div id="home">
  <div class="row">
    <div class="col-sm-12">
      <blockquote>
        <div class="first-part">
          It's the only job I can think of where I get to be both an engineer
          and an artist.
        </div>
        <div class="second-part">
          There's an incredible, rigorous, technical element to it, which I like
          because you have to do very precise thinking. On the other hand, it
          has a wildly creative side where the boundaries of imagination are the
          only real limitation.
        </div>
        <div class="author">-- Andy Hertzfeld</div>
      </blockquote>
    </div>
  </div>
</div>