<article id="impress">
  <h2>Impressum</h2>
  <p>Diese Seiten wurden verbrochen von</p>
  <address>
    Sascha Schneider<br>
    foomy.code@arcor.de
  </address>
  <p class="col-sm-6">
    SirFoomys Welt ist eine private Homepage und dient keinem geschäftsmäßigen Zweck.
    Genau betrachtet dienen diese Seiten eigentlich überhaupt keinem höheren Zweck,
    jedenfalls keinem von dem ich wüsste.
  </p>
  <p class="col-sm-12 small">
    (Selbstdarstellung und geistiger Exhibitionismus sind keine Verwendungszwecke.)
  </p>
</article>