<div class="head1">Administration</div>
<div class="head2"><?php echo $this->translate->_('Gruppen'); ?></div>

<?php echo $this->form; ?>

<table id="rolelist" class="listing">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>beschreibung</th>
    <th></th>
    <th></th>
  </tr>
  <?php foreach ($this->rolelist as $role) { ?>
  <tr id="role_<?php echo $role->getId(); ?>">
    <td class="id"><?php echo $role->getId(); ?></td>
    <td><?php echo $role->getName(); ?></td>
    <td><?php echo $role->getDescription(); ?></td>
    <td class="ico">
      <img src="/img/icon/edit-1.0.png" id="edit_<?php echo $role->getId(); ?>" class="iconEdit" alt="Benutzer bearbeiten." title="Benutzer bearbeiten" />
    </td>
    <td class="ico">
      <img src="/img/icon/delete-1.0.gif" id="delete_<?php echo $role->getId(); ?>" class="iconDelete" alt="Benutzer löschen" title="Benutzer löschen" />
    </td>
  </tr>
  <?php } ?>
</table>
<script type="text/css">
/* <[CDATA[ */
  $(document).ready(function() {
    $('img').live('click', function() {
      var idData = parseElementId($(this).attr('id'));

      $.post(
        idData.action,
        { roleId: idData.id },
        function(data) {
          switch (idData.action) {
            case 'edit':
              if ( ! data.error ) {
                $('#role_id').val(idData.id);
                $('#name').val(data.name);
                $('#description').val(data.description);
              }
              break;

            case 'delete':
              $('#role_'+idData.id).remove();
              break;
          }// switch
        },
        'json'
      );      
    });

    
  });
/* ]]> */
</script>
